FROM docker:20.10 AS docker-cli

FROM public.ecr.aws/lambda/python:3.11
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker

RUN yum update -y
RUN yum -y install git && yum clean all
RUN docker --help
RUN pip3 install boto3

COPY ./lambda/build-api.py .

CMD [ "build-api.handler" ]
